station-goal-fax-paper-name =  Estação Gol

station-goal-fax-paper-header =
    Form NT-No.{ $station }Data: { $date }
     Assinado: CCO-{ $name }
    ╚═╝░░╚══╝░░░╚═╝░░░
    ════════════════════════════════════════
    { $content }
    ════════════════════════════════════════

station-goal-xeno = Caro Comando de Estação, o propósito da sua mudança é construir um Laboratório de Xenobiologia e estudar formas de vida exóticas. Duas câmaras de contenção devem ser construídas de acordo com os seguintes requisitos: 1. Deve ser bem reforçada; 2. Pelo menos uma das câmaras deve estar equipada com um sistema de fornecimento de gás; 3. A entrada deve ser um sistema de câmara de ar de ciclismo para evitar a contaminação. Obter que a Equipa de Salvagem capture pelo menos 2 representantes das formas de vida (por exemplo, carpa espacial) e as transporte para as câmaras acima descritas. Requisitos de captura: 1. A fauna exótica não deve ter lesões críticas no momento da colocação no departamento de pesquisa; 2. Quando a fauna capturada morre, é necessário capturar outra, a clonagem é estritamente proibida. Uma vez que você recolhe a fauna necessária, você deve estudá- la e escrever um relatório sobre as suas propriedades. O relatório deve ser carimbado pelo chefe do departamento e enviado por fax para o Comando Central. Requisitos de Experiência: 1. As actividades de teste podem incluir: trabalhar com gases, fumo, espuma ou injetar reagentes experimentais (e. Cogniine) capturadas em fauna.

station-goal-museum = Caro Comando da estação, o propósito do seu turno é construir um museu, as exposições para as quais serão objetos únicos recolhidos da estação. Abaixo estão os requisitos para o desenho do museu: 1. O museu deve estar estruturalmente ligado à estação por um corredor protegido pelo espaço, ou estar localizado dentro dela; 2. As instalações devem ter um tamanho que lhes permita receber facilmente um grande número de visitantes; 3. As instalações devem ser providas de uma atmosfera padrão, ventilação e fornecimento de energia estável; 4. O número total de exposições deve ser visualmente agradável; 5. As exposições devem ser reforçadas em conformidade com o que está contido nelas. As bebidas exóticas e os pratos que exigem um método extraordinário de produção e/ou ingredientes não padronizados; 2. Cada departamento deve fornecer pelo menos 2 exposições para o fundo do museu; 3. O número total de exposições deve ser de pelo menos 20. As exposições podem incluir: 1. As bebidas exóticas e os pratos que requerem um método extraordinário de produção e/ou os organismos não- padrão; 2. As ferramentas exóticas para o fundo do museu; 3. O número total de exposições deve ser de 20. As instalações de arte (porte, por exemplo, estátuas, pinturas, pinturas, que necessitam de um método de máquinas e

station-goal-area = Caro Comando de Estação, o objetivo do seu turno é aumentar o uso efetivo do espaço na estação, é necessário trazer as instalações abandonadas em forma adequada e encontrar um uso para elas, cada departamento deve equipar e efetivamente usar a área de túneis de manutenção adjacentes, túneis de manutenção suficientemente espaçosos precisam ser convertidos em áreas residenciais, os túneis restantes devem ser providos de coberturas de piso e iluminação adequada, além de ser necessário fornecer um corredor público bem iluminado que ligue todos os compartimentos restaurados e novos quartos.

station-goal-bureaucraticerror = O acesso a este documento é proibido para pessoas que não têm imunidade legal Dear Station Command, informamos que o propósito de seu turno foi perdido em resultado de um erro burocrático. Com esta notícia, o Comando Central lhe dá a oportunidade de atribuir de forma independente uma nova meta para a estação. Novos requisitos de metas: 1. Relevância: O objetivo deve ser relevante e relevante para a situação atual; 2. Engajamento: O objetivo deve exigir a cooperação de tantos departamentos quanto possível nos planos; 3. Escopo: O objetivo deve envolver suficientes, mas não excessivas, quantidades de trabalho para garantir a efetiva realização da tarefa. Por favor, note que a distribuição do conteúdo deste documento a pessoas que não têm imunidade legal é estritamente proibida devido à possibilidade de desacreditar a gestão da Corporação. Portanto, para apresentar um novo objetivo à tripulação, o comando deve contatar o Comando Central para aprovação de suas ideias.

station-goal-anomalies = Caro Comando de Estação, o propósito de sua mudança é fornecer novas informações sobre anomalias a NanoTrasen, é necessário realizar estudos experimentais que visem testar as consequências do colapso de pelo menos 4 anomalias únicas, durante ou após os experimentos, é necessário isolar e documentar as anomalias acima mencionadas, requisitos do documento: 1. o nome oficial da anomalia, 2. a descrição física, 3. as propriedades passivas, 4. a reação da anomalia a diferentes partículas, 5. as consequências do colapso, 6. a localização da anomalia, o documento deve ser certificado pelo selo do supervisor e enviado para o Comando Central.

station-goal-combat = Caro Comando da Estação, devido ao aumento dos ataques de navios piratas neste setor, o objetivo do seu turno é aumentar a prontidão de combate global da estação. Necessário: 1. Organizar uma inspeção de cada ser senciente e carga que chega ou sai da estação. 2. Construir ou modificar um posto de controle de segurança existente em chegadas e partidas. O posto de controle deve ser capaz de bloquear completamente os portos da parte principal da estação. Cada um dos postos de controle acima deve ter pelo menos uma cela para a detenção temporária dos detidos. 3. Organizar um armazenamento de armas de reserva na parte oposta da estação a partir da brig. O arsenal do cofre deve ter armas e equipamentos suficientes para equipar totalmente todo o pessoal de segurança. 4. Organizar o recrutamento de um novo subdepartamento de segurança. Os membros do esquadrão devem ser recrutados da tripulação da estação. Recrutamento deve ser realizado em uma base voluntária-compulsória. Composição do esquadrão: 1 Médico de Campo; 1 Engenheiro de Campo; 3 Posto de Combate; Todos os membros do esquadrão devem ser recrutados da equipe devem ser treinados em todas as habilidades necessárias para realizar o combate e o grupo de treinamento.

station-goal-shuttle = Caro Comando da Estação, o objetivo do seu turno é construir um ônibus espacial capaz de ser pilotado. Requisitos do ônibus espacial: 1. O ônibus espacial deve ter uma ponte trancada; uma sala médica com os suprimentos médicos necessários e equipamentos químicos; uma loja de suprimentos cercado por material reforçado; uma sala de tripulação com pelo menos 12 lugares. 2. Deve haver uma sala intermediária entre a comporta de atracação e as salas principais para evitar possível despressurização. 3. O ônibus espacial deve ter uma atmosfera padrão, e também vários recipientes de gás aéreo para mantê-lo. 4. O ônibus espacial deve ser capaz de mover-se em todas as direções (para frente, para trás, para os lados) e virar razoavelmente bem. Após a conclusão, a tripulação do ônibus deve ser recrutada do pessoal da estação. A tripulação do transporte deve incluir: 1 piloto; 2 engenheiros; 1 médico/quimista; 1 oficial de segurança. O ônibus espacial deve levar todos os representantes do Comando da estação como passageiros e, em paralelo com o transporte de evacuação, ir para a estação de comando central.

station-goal-singularity = Caro Comando da Estação, o objetivo do seu turno é construir um gerador baseado na singularidade gravitacional, os requisitos de projeto são: 1. A estrutura deve ser localizada a uma distância significativa da estação. 2. A estrutura deve ser protegida de meteoritos e detritos espaciais. 3. O campo de contenção deve ser capaz de evitar a perda de uma singularidade classe 3.

station-goal-solarpanels = Caro Comando da Estação, o propósito do seu turno é organizar um sistema de energia de reserva, o seguinte trabalho é necessário: 1. Construa dois novos ramos de painéis solares, e aloque uma área para um compartimento com baterias de reposição, que deve acomodar pelo menos 3 SMEs totalmente carregados, que não devem ser conectados ao sistema de energia principal da estação, a menos que seja necessário.

station-goal-artifacts = Caro Comando da Estação, o propósito de sua mudança é fornecer novas informações sobre artefatos alienígenas para NanoTrasen, é necessário organizar o trabalho de salvadores para procurar e entregar artefatos dos destroços ao redor da estação ou expedições, após a entrega dos artefatos, eles devem ser transferidos para um recipiente especial para o departamento de pesquisa, é necessário entregar pelo menos 2 artefatos totalmente estudados e documentados na nave de evacuação em unidades especiais de contenção, informações recomendadas para o documento, nome do artefato, 2. descrição física, 3. propriedades do objeto, 4. localização do local onde o artefato foi encontrado, 5. notas adicionais, o documento deve ser certificado pelo carimbo do supervisor.

station-goal-storage = Caro Comando da Estação, o propósito de sua mudança é construir uma instalação de armazenamento orbital com suprimentos e tecnologia, o armazenamento deve ser colocado no espaço separadamente da estação principal, certifique-se de que seu projeto é forte, um meteorito aleatório não deve danificá-lo.

station-goal-zoo = Caro Comando da Estação, o propósito do seu turno é melhorar o valor recreativo do pessoal da estação, é necessário construir um zoológico com pelo menos 5 compartimentos contendo diferentes tipos de animais ordenados do departamento de abastecimento, fornecer aos animais comida, pelo menos um robô de limpeza em cada recinto, e tudo o que for necessário para a vida, dependendo do tipo de animal, também é necessário construir uma casa de banho para os animais, vapor de água deve ser fornecido por Técnicos Atmosféricos, após a conclusão do zoológico, é necessário fornecer à tripulação pelo menos 20 minutos de tempo livre do trabalho para que possam visitar o novo zoológico.

station-goal-labor = Caro Comando da Estação, o propósito do seu turno é aumentar a motivação do pessoal para o crescimento da produtividade do trabalho. Isto requer que cada um dos chefes durante o turno monitore de perto o desempenho das tarefas de seus funcionários e avalie-os. Após o tempo estabelecido pelo Comando para avaliação, em cada um dos departamentos, o melhor, na opinião do chefe, empregado deve ser selecionado, que será convidado para um jantar, onde o pessoal do Comando será obrigado a atribuir-lhes uma medalha e um prêmio. Os chefes devem fornecer um relatório indicando a posição do funcionário e os méritos para o turno. Bebidas e refeições devem ser preparadas para o jantar, bem como, se possível, vários eventos de entretenimento que permitam a presença de atores e músicos. Para a duração da celebração, a sala de jantar ou outro local escolhido para o evento deve ser inacessível ao resto da tripulação. A duração do turno para uma avaliação mais precisa do trabalho do pessoal deve ser definida pelo pessoal do Comando. Após o jantar alguém deve anunciar o fim do turno e chamar a evacuação.

station-goal-lectures = Caro Comando da Estação, o propósito do seu turno é realizar uma série de eventos dentro do quadro do plano da Corporação para aumentar o conhecimento dos seus funcionários. O pessoal do Comando é instruído a organizar uma plataforma para palestras públicas, se não existir, criar uma próxima entrada da ponte. O local deve ser equipado com um grande estágio suficiente para alto-falantes no meio, um pódio para o apresentador para um lado dele, uma abundância de lugares para os convidados, e um balcão / mesa especial para brochuras na entrada. Um anfitrião / organizador do evento também deve ser selecionado. Cada departamento é necessário apresentar um grupo de funcionários que consiste em pelo menos 2 pessoas. Funcionários selecionados, sob a supervisão do chefe do departamento, deve preparar uma breve palestra / apresentação sobre um tema específico dentro de sua especialização (por exemplo, o dano das drogas e sua razão para a criminalização, o efeito de fumar no corpo, agindo, preço do produto, cozinhar etc.), preferencialmente com materiais de demonstração, e em pelo menos 10 folhetos, em que o discurso deve ser indicado pelo pessoal para o evento de chamada.

station-goal-fishing = Caro Comando de Estação, o objetivo principal para esta mudança é maximizar a utilização das capacidades de pesca da estação, e precisamos de um alto volume de atividade de pesca para facilitar o estudo da fauna aquática local, seu objetivo principal é documentar todas as formas de vida aquática presentes na estação, para apoiar esta iniciativa, nós encorajamos você a construir uma doca ou cais para proporcionar fácil acesso aos pontos de pesca, permitindo espaço, além disso, tomar uma liberdade construtiva para desenvolver esta área em um espaço recreativo acolhedor, oferecendo à tripulação um ambiente agradável para relaxar durante o seu tempo de inatividade.

station-goal-stripclub = O objetivo principal desta mudança é utilizar espaço extra em nossas estações de manutenção para construir um clube de strip, seu objetivo principal é construir um clube de strip em nossas estações de espaço não processado, como uma sala nos túneis de manutenção, e dar total liberdade criativa para construir como você melhor vê-lo adequado para a população da estação, sendo necessário que você rotule corretamente a área como tal usando um pintor de spray, recomendamos utilizar alguns funcionários de serviço ou passageiros para dirigir o clube e quaisquer outras funções que você queira adicionar a ele, como um bar ou cozinha.
